"""Seed data for Silkroute Naturals."""
from datetime import datetime, timezone
import uuid

def NOW() -> str:
    return datetime.now(timezone.utc).isoformat()


def make_id() -> str:
    return str(uuid.uuid4())


PRODUCTS = [
    {
        "id": make_id(),
        "slug": "premium-mamra-almonds",
        "name": "Premium Mamra Almonds",
        "origin": "Afghanistan",
        "category": "almonds",
        "tagline": "Renowned for exceptional flavor and rich oil content",
        "description": "Hand-harvested from the foothills of the Hindu Kush, our Mamra almonds are smaller, denser, and richer in oil than commercial varieties — the original almond of Persian poetry. Slow-dried under the sun for an aroma that lingers.",
        "benefits": ["High oil content", "Cold-stored freshness", "Single-origin Afghanistan", "Hand-graded"],
        "price": 1450,
        "compare_at_price": 1750,
        "weight": "250g",
        "stock": 48,
        "images": [
            "https://images.unsplash.com/photo-1633677491262-0a51b9851f46",
            "https://images.pexels.com/photos/5425018/pexels-photo-5425018.jpeg",
        ],
        "featured": True,
        "story": "From the orchards of Kunduz to your table — a 2,000-year-old harvest tradition.",
        "created_at": NOW(),
    },
    {
        "id": make_id(),
        "slug": "royal-pistachios",
        "name": "Royal Pistachios — Akbari",
        "origin": "Iran",
        "category": "pistachios",
        "tagline": "Sourced from the fertile regions of Iran",
        "description": "The largest grade of Iranian pistachios, prized in Mughal courts for their elongated form and emerald kernels. We import them whole-shell, lightly salted in Himalayan pink salt.",
        "benefits": ["Extra-large grade", "Naturally split shells", "Himalayan salt-cured", "Single-origin Rafsanjan"],
        "price": 1890,
        "compare_at_price": 2200,
        "weight": "250g",
        "stock": 32,
        "images": [
            "https://images.unsplash.com/photo-1633677491262-0a51b9851f46",
            "https://images.pexels.com/photos/34746904/pexels-photo-34746904.jpeg",
        ],
        "featured": True,
        "story": "Rafsanjan — the pistachio capital of the world for over 1,500 years.",
        "created_at": NOW(),
    },
    {
        "id": make_id(),
        "slug": "imperial-hazelnuts",
        "name": "Imperial Hazelnuts",
        "origin": "Turkey",
        "category": "hazelnuts",
        "tagline": "Harvested from the lush orchards of Turkey",
        "description": "Roasted to a deep amber in small batches, our Black Sea hazelnuts have an unmistakable creamy butterness. Perfect on their own or stirred into morning porridge.",
        "benefits": ["Slow-roasted", "Black Sea coast origin", "Skinned by hand", "No preservatives"],
        "price": 980,
        "compare_at_price": 1150,
        "weight": "250g",
        "stock": 60,
        "images": [
            "https://images.pexels.com/photos/5425018/pexels-photo-5425018.jpeg",
        ],
        "featured": True,
        "story": "The Black Sea coast — where Roman emperors once sourced their feasts.",
        "created_at": NOW(),
    },
    {
        "id": make_id(),
        "slug": "golden-cashews",
        "name": "Golden Cashews — W240",
        "origin": "India",
        "category": "cashews",
        "tagline": "Delicate, buttery flavor and crunchy texture",
        "description": "W240 grade — the largest, whitest, and most buttery cashews from the Konkan coast. Steam-cooked, never bleached.",
        "benefits": ["W240 export grade", "Konkan coast origin", "Non-GMO", "No bleaching agents"],
        "price": 850,
        "compare_at_price": 1000,
        "weight": "250g",
        "stock": 84,
        "images": [
            "https://images.pexels.com/photos/5425018/pexels-photo-5425018.jpeg",
        ],
        "featured": True,
        "story": "From the coastal groves of Goa and Karnataka — sun-ripened, hand-shelled.",
        "created_at": NOW(),
    },
    {
        "id": make_id(),
        "slug": "medjool-dates",
        "name": "Medjool Dates — Royal Reserve",
        "origin": "Morocco",
        "category": "dates",
        "tagline": "Natural sweetness and luxurious texture",
        "description": "The 'King of Dates' — soft, caramel-sweet, with a velvet finish. Sourced from the Tafilalet oasis and packed within 72 hours of harvest.",
        "benefits": ["Jumbo grade", "Tafilalet oasis origin", "Naturally caramel-sweet", "No added sugar"],
        "price": 1290,
        "compare_at_price": 1500,
        "weight": "500g",
        "stock": 40,
        "images": [
            "https://images.unsplash.com/photo-1708335008926-e8b898da2ae9",
            "https://images.pexels.com/photos/34746904/pexels-photo-34746904.jpeg",
        ],
        "featured": True,
        "story": "The Tafilalet oasis — where caravans paused on the ancient trans-Saharan route.",
        "created_at": NOW(),
    },
    {
        "id": make_id(),
        "slug": "kashmiri-saffron",
        "name": "Kashmiri Saffron — Mongra",
        "origin": "India",
        "category": "spices",
        "tagline": "Deep color, intense aroma, exquisite flavor",
        "description": "Mongra-grade saffron from the Pampore plateau — only the deep crimson tips of the stigma. The world's most coveted spice, by weight more valuable than gold.",
        "benefits": ["Mongra grade", "Pampore plateau origin", "ISO 3632 Category I", "Only stigma tips"],
        "price": 2450,
        "compare_at_price": 2900,
        "weight": "2g",
        "stock": 24,
        "images": [
            "https://images.pexels.com/photos/34746904/pexels-photo-34746904.jpeg",
        ],
        "featured": True,
        "story": "The Pampore plateau — where saffron has bloomed for over 2,500 years.",
        "created_at": NOW(),
    },
    {
        "id": make_id(),
        "slug": "anjeer-figs",
        "name": "Sun-Dried Anjeer",
        "origin": "Turkey",
        "category": "dried-fruits",
        "tagline": "Sun-dried whole figs, soft and honeyed",
        "description": "Whole Lerida figs from the Aegean valleys, sun-cured on woven trays for 14 days. Soft as silk, sweet as honey.",
        "benefits": ["Aegean valley origin", "14-day sun cure", "No sulphur", "Whole-fig grade"],
        "price": 720,
        "compare_at_price": 900,
        "weight": "250g",
        "stock": 56,
        "images": [
            "https://images.pexels.com/photos/5425018/pexels-photo-5425018.jpeg",
        ],
        "featured": False,
        "story": "Lerida figs — once tribute to the Ottoman court.",
        "created_at": NOW(),
    },
    {
        "id": make_id(),
        "slug": "walnut-halves",
        "name": "Kashmiri Walnut Halves",
        "origin": "India",
        "category": "walnuts",
        "tagline": "Light kernels, buttery and crisp",
        "description": "Light-amber walnut halves from the high orchards of Kupwara. Cracked by hand to preserve whole halves.",
        "benefits": ["Light kernel grade", "Kupwara orchards", "Hand-cracked halves", "Cold-stored"],
        "price": 1180,
        "compare_at_price": 1400,
        "weight": "250g",
        "stock": 38,
        "images": [
            "https://images.pexels.com/photos/5425018/pexels-photo-5425018.jpeg",
        ],
        "featured": False,
        "story": "Kupwara — at 6,500 ft, where walnuts ripen slow under Himalayan skies.",
        "created_at": NOW(),
    },
    {
        "id": make_id(),
        "slug": "apricot-kernels",
        "name": "Hunza Apricot Kernels",
        "origin": "Afghanistan",
        "category": "dried-fruits",
        "tagline": "Sweet kernels from the Hunza valley",
        "description": "Naturally sweet apricot kernels from the Hunza valley — a quiet luxury, softly almond-like with a stone-fruit aroma.",
        "benefits": ["Hunza valley origin", "Naturally sweet", "Sun-dried", "Whole kernels"],
        "price": 890,
        "compare_at_price": 1050,
        "weight": "200g",
        "stock": 44,
        "images": [
            "https://images.unsplash.com/photo-1633677491262-0a51b9851f46",
        ],
        "featured": False,
        "story": "The Hunza valley — fabled home of centenarians, on the old Silk Route.",
        "created_at": NOW(),
    },
    {
        "id": make_id(),
        "slug": "raisins-monukka",
        "name": "Monukka Raisins",
        "origin": "Afghanistan",
        "category": "dried-fruits",
        "tagline": "Long, plump, naturally sun-cured",
        "description": "Long Monukka raisins from the Shomali plain. Naturally seedless, sun-dried in stone houses called 'kishmish khana'.",
        "benefits": ["Shomali plain origin", "Naturally seedless", "Stone-house dried", "No added oil"],
        "price": 540,
        "compare_at_price": 650,
        "weight": "250g",
        "stock": 72,
        "images": [
            "https://images.pexels.com/photos/5425018/pexels-photo-5425018.jpeg",
        ],
        "featured": False,
        "story": "Shomali — a plain dotted with 'kishmish khana', the ancient drying houses.",
        "created_at": NOW(),
    },
]


COUPONS = [
    {"id": make_id(), "code": "WELCOME10", "discount_type": "percent", "discount_value": 10, "min_order": 999, "active": True, "description": "10% off your first order over ₹999", "created_at": NOW()},
    {"id": make_id(), "code": "SILKROUTE15", "discount_type": "percent", "discount_value": 15, "min_order": 2499, "active": True, "description": "15% off orders over ₹2,499", "created_at": NOW()},
    {"id": make_id(), "code": "GIFT500", "discount_type": "flat", "discount_value": 500, "min_order": 3499, "active": True, "description": "Flat ₹500 off on orders over ₹3,499", "created_at": NOW()},
]


BLOG_POSTS = [
    {
        "id": make_id(),
        "slug": "the-silk-route-and-the-art-of-the-almond",
        "title": "The Silk Route and the Art of the Almond",
        "excerpt": "How a single fruit travelled across continents — and how it still arrives at your door, unchanged.",
        "cover_image": "https://images.pexels.com/photos/9494903/pexels-photo-9494903.jpeg",
        "content": "Long before refrigeration, before borders, before the spice routes had names, almonds travelled. From the foothills of the Hindu Kush to the imperial kitchens of Persia, and then onward — wrapped in silk, sealed in clay — to the Mediterranean...\n\nWe still source ours from the same orchards. The same trees, the same families, the same slow drying under the sun.",
        "author": "Silkroute Editorial",
        "published_at": NOW(),
    },
    {
        "id": make_id(),
        "slug": "why-mamra-is-different",
        "title": "Why Mamra Is Different",
        "excerpt": "Smaller. Denser. Oilier. Why connoisseurs always reach for Mamra.",
        "cover_image": "https://images.unsplash.com/photo-1633677491262-0a51b9851f46",
        "content": "Most almonds in the world today are from California. Mamra is not. Mamra is a heritage cultivar — slow-growing, low-yielding, intensely flavorful. The kind of almond you eat one at a time...\n\nIn Persian cuisine, Mamra is the only almond used for ranginak, a date-and-almond pastry. The denseness matters. The oil matters.",
        "author": "Silkroute Editorial",
        "published_at": NOW(),
    },
    {
        "id": make_id(),
        "slug": "the-experience-center",
        "title": "Inside the Experience Center",
        "excerpt": "Cold-press oils, fresh nut butters, tasting flights — our Bengaluru atelier opens its doors.",
        "cover_image": "https://images.pexels.com/photos/35045845/pexels-photo-35045845.jpeg",
        "content": "We built the Experience Center for those who want to taste before they buy. Our cold-press oil mill runs three times a week. The nut butter machine grinds to order — almond, cashew, pistachio, hazelnut...\n\nBook a tasting flight: five origins, five textures, fifty minutes. By appointment.",
        "author": "Silkroute Editorial",
        "published_at": NOW(),
    },
    {
        "id": make_id(),
        "slug": "saffron-the-thread-of-gold",
        "title": "Saffron — The Thread of Gold",
        "excerpt": "Why one gram costs more than gold. And why it should.",
        "cover_image": "https://images.pexels.com/photos/34746904/pexels-photo-34746904.jpeg",
        "content": "It takes 150,000 crocus flowers to make one kilogram of saffron. Each flower yields three crimson stigmas. Each stigma is hand-plucked at dawn, before the sun touches it...\n\nMongra is the highest grade — only the deep red tips, no yellow style. We source from one cooperative in Pampore. That's it.",
        "author": "Silkroute Editorial",
        "published_at": NOW(),
    },
]


BANNERS = [
    {
        "id": make_id(),
        "title": "Treasures from the Ancient Silk Route",
        "subtitle": "Single-origin dry fruits, slow-cured. From Afghanistan, Iran, Turkey, Morocco, India.",
        "cta_label": "Discover the Journey",
        "cta_link": "/our-story",
        "image": "https://images.pexels.com/photos/9494903/pexels-photo-9494903.jpeg",
        "active": True,
        "created_at": NOW(),
    },
    {
        "id": make_id(),
        "title": "Custom Nut Butter Atelier",
        "subtitle": "Designed by you. Stone-ground to order. Delivered in 7 days.",
        "cta_label": "Build Your Jar",
        "cta_link": "/nut-butter-builder",
        "image": "https://images.pexels.com/photos/33657317/pexels-photo-33657317.jpeg",
        "active": True,
        "created_at": NOW(),
    },
]
